codecov:
  require_ci_to_pass: false
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  precision: 2
  range:
    - 70.0
    - 100.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: true
github_checks:
  annotations: true
ignore:
  - ^.building.*
  - ^.debug.*
  - ^.github.*
  - ^.testing.*
  - ^.vscode.*
  - ^docs.*
  - ^.gitattritbutes.*
  - ^.gitignore.*
  - ^.luacov.*
  - ^CODE_OF_CONDUCT.md.*
  - ^codecov.yml.*
  - ^CONTRIBUTING.md.*
  - ^coveralls.yml.*
  - ^LICENSE.*
  - ^README.md.*
  - ^SUPPORT.md.*
  - ^luarocks-3.8.0/.codecov.yml.*