name: Changelog
on:
  tag:
    types:
      - created
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏ Generate release or tag changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dateFormat: "%d.%m.%Y"
          output: "CHANGELOG.md"
          issueLineLabels: "ALL"
          breakingLabels: "backwards-incompatible,breaking,rework,refactor"