name: Increase version on pull request
on:
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  copy_label_and_increase_version:
    name: Copy label and increase version
    runs-on: ubuntu-latest
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Fetch associated issue context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          for issueNumber in ${{ steps.links.outputs.issues }}
          do
            echo "issueNumber="$issueNumber
            issueUrl=$( echo ${{ github.event.pull_request.base.repo.issues_url }} | sed "s/{\/number}/\/$issueNumber/g" )
            echo "issueUrl="$issueUrl
            labels=$( curl $issueUrl | jq '.labels')
            echo "labels="$labels
        
            for label in $( echo $labels | jq -r '.[] | .name' )
            do
              echo "label="$label
              labelNames="${labelNames:+$labelNames,}\"$label\""
            done
        
          done
          echo "labelNames="$labelNames
        
          echo `curl --verbose --request POST \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Content-Type: application/json' \
          --url 'https://api.github.com/repos/${{github.repository}}/issues/${{github.event.number}}/labels' \
          -d '{"labels":[echo $labelNames]}'`
        
          curlResponse=`curl --verbose --request POST \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Content-Type: application/json' \
          --url 'https://api.github.com/repos/${{github.repository}}/issues/${{github.event.number}}/labels' \
          -d '{"labels":[echo $labelNames]}'`
        
          echo "curlResponse="$curlResponse
        
          if [[ $curlResponse == *"200"* ]]
          then
            echo "SUCCESS"
          else
            echo "FAILURE"
            exit 1
          fi
      
      - name: echo labelNames
        run: |
          echo ${{ env.labelNames }}
          env

#      - name: Add labels
#        uses: actions/github-script@v6.1.0
#        with:
#          script: |
#            echo "${{ env.labelNames }}"
#            echo "$labelNames"
#
#            for issueNumber in ${{ steps.links.outputs.issues }}
#            do
#              echo "issueNumber="$issueNumber
#              issueUrl=$( echo ${{ github.event.pull_request.base.repo.issues_url }} | sed "s/{\/number}/\/$issueNumber/g" )
#              echo "issueUrl="$issueUrl
#              labels=$( curl $issueUrl | jq '.labels')
#              echo "labels="$labels
#
#              for label in $( echo $labels | jq -r '.[] | .name' )
#              do
#                echo "label="$label
#                labelNames="${labelNames:+$labelNames, }'$label'"
#              done
#
#            done
#            echo "labelNames="$labelNames
#            echo [$labelNames]
#
#            github.rest.issues.addLabels({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo:context.repo.repo,
#              labels: [$labelNames]
#            })

#      - name: Add labels
#        run: |
#          labels=[]
#          for issueNumber in ${{ steps.links.outputs.issues }}
#          do
#            echo ${{ env."issueContext${issueNumber}" }}
#            issueContext="issueContext${issueNumber}"#$(echo $issueNumber | sed "s/issueContext//g")
#            echo $issueContext
#            for label in $(echo $issueContext | sed "s/,/ /g")
#            do
#              echo $label
#              labels+=$(echo "\"$label\",")
#            done
#          done
#          echo $labels
#
#          github.rest.issues.addLabels({
#            issue_number: context.issue.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            labels: [echo $labels]
#          })