name: Increase version on pull request
on:
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  copy_label_and_increase_version:
    name: Copy label and increase version
    runs-on: ubuntu-latest
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      #- name: Output linked Issue list
      #  run: echo "${{ steps.links.outputs.issues }}"
      #- name: Dump GitHub context
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      - name: Fetch associated issue context
        run: |
          for issueNumber in ${{ steps.links.outputs.issues }}
          do
            echo $issueNumber
            issueUrl=$( echo ${{ github.event.pull_request.base.repo.issues_url }} | sed "s/{\/number}/\/$issueNumber/g" )
            echo $issueUrl
            labels=$( curl $issueUrl | jq '.labels')
            echo $labels
            echo "issueContext$issueNumber=$(echo $labels)" >> $GITHUB_ENV
          done
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Add labels
        uses: actions/github-script@v6
        with:
          script: |
            for issueNumber in ${{ steps.links.outputs.issues }}
            do
              echo "issueContext${issueNumber}"
            done
      - name: Add labels
        run: |
          labels = []
          for issueNumber in ${{ steps.links.outputs.issues }}
          do
            issueContext=$(echo $issueNumber | sed "s/issueContext//g")
            echo $issueContext
            for label in $(echo $issueContext | sed "s/,/ /g")
            do
              echo $label
              labels+=$(echo "\"$label\",")
            done
          done
          echo $labels

          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [echo $labels]
          })