name: Increase version on pull request
on:
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  copy_label_and_increase_version:
    name: Copy label and increase version
    runs-on: ubuntu-latest
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Fetch associated issue context
        run: |
          labelNames=""
          for issueNumber in ${{ steps.links.outputs.issues }}
          do
            echo "issueNumber="$issueNumber
            issueUrl=$( echo ${{ github.event.pull_request.base.repo.issues_url }} | sed "s/{\/number}/\/$issueNumber/g" )
            echo "issueUrl="$issueUrl
            labels=$( curl $issueUrl | jq '.labels')
            echo "labels="$labels
          
          labelNames="["
            for label in $( echo $labels | jq -r '.[] | .name' )
            do
              echo "label="$label
              labelNames+="'$label',"
            done
          labelNames= echo($labelNames | sed -e '$s/,$//')
          labelNames+="]"
          done
          echo "labelNames="$labelNames
          echo "labelNames=$labelNames" >> GITHUB_ENV

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Add labels
        uses: actions/github-script@v6
        with:
          script: |
            echo "${{ env.labelNames }}"
            echo "$labelNames"
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo:context.repo.repo,
              labels: echo "${{ env.labelNames }}"
            })

#      - name: Add labels
#        run: |
#          labels=[]
#          for issueNumber in ${{ steps.links.outputs.issues }}
#          do
#            echo ${{ env."issueContext${issueNumber}" }}
#            issueContext="issueContext${issueNumber}"#$(echo $issueNumber | sed "s/issueContext//g")
#            echo $issueContext
#            for label in $(echo $issueContext | sed "s/,/ /g")
#            do
#              echo $label
#              labels+=$(echo "\"$label\",")
#            done
#          done
#          echo $labels
#
#          github.rest.issues.addLabels({
#            issue_number: context.issue.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            labels: [echo $labels]
#          })