name: Increase version on pull request
on:
  pull_request:
    types: [ opened, edited, synchronize ]
jobs:
  copy_label_and_increase_version:
    name: Copy label and increase version
    runs-on: ubuntu-latest
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Output linked Issue list
        run: echo "${{ steps.links.outputs.issues }}"
      #- name: Dump GitHub context
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      - name: Copy label from issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #gh auth logout #https://github.com/cli/cli/issues/494
          #gh auth login
          #cd ${{ github.workspace }}
          #gh issue view ${{ steps.links.outputs.issues }} --json "labels"
          for issueNumber in ${{ steps.links.outputs.issues }}
          do
            issueUrl=$( ${{event.pull_request.base.repo.issues_url}} | sed "s/{\/number}/\/123/g" )
            labels=$(toJSON(curl issueUrl).labels)
          done
          
