name: Windows Lua Unit Testing

on: [ push, pull_request ]

jobs:
  lua-unit-testing-on-windows-latest:
    name: "LuaUnit on Windows-latest (mingw32)"
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Run LuaUnit 3.4
        id: lua_unit_tests
        run: |
          cd ${{ github.workspace}}\mods\noita-mp\
          luarocks test > result.log
        
          # https://timheuer.com/blog/manually-force-a-failure-in-github-action-step/
          $testFail = Select-String -Path ${{ github.workspace }}\mods\noita-mp\result.log -Pattern 'FAIL' -CaseSensitive
          echo "{fail}={$testFail}" >> $GITHUB_OUTPUT
        
          $testError = Select-String -Path ${{ github.workspace }}\mods\noita-mp\result.log -Pattern 'ERROR' -CaseSensitive
          echo "{error}={$testError}" >> $GITHUB_OUTPUT
        
          $notFound = Get-Content -Path ${{ github.workspace }}\mods\noita-mp\result.log
          echo "{not_found}={$notFound}" >> $GITHUB_OUTPUT
      
      - name: Unit test failed?
        if: ${{ steps.lua_unit_tests.outputs.fail != '' || steps.lua_unit_tests.outputs.error != '' || steps.lua_unit_tests.outputs.not_found == '' }}
        run: |
          echo "steps.lua_unit_tests.outputs.fail = ${{ steps.lua_unit_tests.outputs.fail }}"
          echo "steps.lua_unit_tests.outputs.error = ${{ steps.lua_unit_tests.outputs.error }}"
          echo "steps.lua_unit_tests.outputs.not_found = ${{ steps.lua_unit_tests.outputs.not_found }}"
          echo "Unit tests failed!"
          # exit 1
      
      - name: Install dependencies
        run: |
          cd ${{ github.workspace}}\mods\noita-mp\
          luarocks install luacov
          luarocks install lua-path
          luarocks install dkjson
          luarocks install luafilesystem
          luarocks install luacov-coveralls
      
      - name: Generate coverage report with luacov
        run: |
          dir -Path ${{ github.workspace }}\.testing\tests -Filter *.lua -Recurse | %{& '${{ env.lua_install_bin_dir }}\luajit.exe' -lluacov $_.FullName -o text --verbose }
        
          Start-Process -FilePath "${{ env.lua_install_bin_dir }}\luacov.bat" -Wait -NoNewWindow
      
      # - name: Generate coverage report with luacov-coveralls
      #   shell: cmd
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERALLS_DEBUG: true
      #   run: |
      #     ${{ env.lua_install_bin_dir }}\luacov-coveralls.bat -v
      
      - name: Fix codecov path issue
        # shell: pwsh
        run: |
          # ls -R
          # $content = Get-Content -Path ${{ github.workspace }}/luacov.report.out
          # $content = $content.Replace("\", "/")
          # $content > ${{ github.workspace }}/luacov.report.out
          # Write-Host $content
          
          $(cat ${{ github.workspace }}/luacov.report.out | sed -e 's_\\_/_g') > ${{ github.workspace }}/luacov.report.out
          cat ${{ github.workspace }}/luacov.report.out
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ github.workspace }}
          flags: unittesting
          functionalities: network
          name: Windows Lua Unit Testing
          verbose: true
